### ISSUE TITLE
Videos saved within ~/ aka "Home" are being saved as hidden files with unexpected file names

### ISSUE THREAD

**Issue by NintendoManiac64** [flathub/org.avidemux.Avidemux#22] opened 2024-03-15 20:54 UTC
Tested with the live ISO of Mint 21.3 Xfce.

Simply put, saving a video anywhere in ~/ aka "Home" results in it being saved as a hidden file with a file name that is unexpected.

Here's a short video clip demonstrating the issue (Avidemux was simply installed from Mint's "Software manager" but I skipped recording that step because my internet is kind of slow so it took like 10+ minutes to install):

[video.webm](https://github.com/flathub/org.avidemux.Avidemux/assets/11896003/292ad2db-1952-41e1-bc06-da7fe99e1f4b)

**Comment by guihkx** [comment] 2024-03-15 21:11
Hi,

This issue is, unfortunately, not reproducible for me on KDE Plasma 6.

Do you know what [XDG Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/docs/index.html) implementation you have installed? You can probably check that with this command:

```sh
dpkg -l | grep ^ii | awk '{print $2 $3}' | grep 'xdg-desktop-portal'
```

**Comment by guihkx** [comment] 2024-03-15 21:13
In the meantime, you can always manually allow Avidemux unrestricted access to the entire filesystem with:

```sh
flatpak override --user --filesystem=host org.avidemux.Avidemux
```

Keep in mind that the permission above will defeat the Flatpak sandbox.

**Comment by NintendoManiac64** [comment] 2024-03-15 21:14
> This issue is, unfortunately, not reproducible for me on KDE Plasma 6.

This was the live ISO of Linux Mint 21.3 Xfce—should I re-record the video booting said live ISO from scratch, including the 10+ minutes of installing the Avidemux flatpak?

**Comment by guihkx** [comment] 2024-03-15 21:17
> This was the live ISO of Linux Mint 21.3 Xfce—should I re-record the video booting said live ISO from scratch, including the 10+ minutes of installing the Avidemux flatpak?

That won't be necessary.

Instead, if possible, please post the information I asked you.

I asked that because I suspect this issue lies on either:

- How old is the `xdg-desktop-portal` package on Linux Mint 21.3
- What backend implementation of the XDG Desktop Portal is being used (and their version, too)

**Comment by NintendoManiac64** [comment] 2024-03-15 21:27
> Hi,
> 
> This issue is, unfortunately, not reproducible for me on KDE Plasma 6.
> 
> Do you know what [XDG Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/docs/index.html) implementation(s) you have installed? You can probably check that with this command:
> 
> ```shell
> dpkg -l | grep ^ii | awk '{print $2 $3}' | grep 'xdg-desktop-portal'
> ```

Live Mint 21.3 Xfce returns the following:
````
xdg-desktop-portal1.14.4-1ubuntu2~22.04.1
xdg-desktop-portal-gtk1.14.0-1build1
xdg-desktop-portal-xapp1.0.3+victoria
````

**Comment by guihkx** [comment] 2024-03-15 22:03
Got it, thanks.

I'm 99% sure the issue is caused by a bug in xdg-desktop-portal that's been fixed in newer releases.

The version included in Mint 21.3 is way too old at this point.

Unfortunately, it won't be that easy to verify my suspicion:

One would have to build and install the latest version of xdg-desktop-portal from source (I couldn't find any PPAs), and then reboot their computer, which makes this impossible when using the Live-CD image.

But even if upgrading xdg-desktop-portal fixes the issue, this will remain a problem for the majority of Linux Mint user.

On the other hand, I don't like the idea of allowing [unrestricted filesystem access](https://github.com/flathub/org.avidemux.Avidemux/issues/22#issuecomment-2000447597), by default for everyone, just because older distros are relying on buggy versions of xdg-desktop-portal.

@NintendoManiac64 Do you of any other app that is also affected by this?

**Comment by NintendoManiac64** [comment] 2024-03-15 23:01
> One would have to build and install the latest version of xdg-desktop-portal from source (I couldn't find any PPAs), and then reboot their computer, which makes this impossible when using the Live-CD image

I'm only using the live ISO for testing purposes since my own local installation of Mint is actually the older Mint 20.3 Xfce since I initially ran into the issue on there and then went to check and see if it was fixed in Mint 21.3 Xfce (which apparently it's not).

Interestingly, when I went to test with a completely different video on my local Mint 20.3 installation, it didn't have this issue? And doing a sanity check with the live ISO of Mint 21.3 Xfce showed that the issue still happened there even with this other file, so... weirdness.

**Comment by guihkx** [comment] 2024-03-15 23:10
>when I went to test with a completely different video on my local Mint 20.3 installation, it didn't have this issue?

Did that happen over a week ago?

Because before that, this package did have unrestricted access to the filesystem by default, through the `--filesystem=host` Flatpak permission.

So this is most likely the reason why you didn't experience such problems before.

But like I said in previous comments, that behavior can still be restored pretty easily with a permission override.

I just don't think I should re-enable that permission by default, affecting even people who don't have the issue and prefer a stronger sandbox policy.

**Comment by NintendoManiac64** [comment] 2024-03-15 23:12
> Did that happen over a week ago?

No I did all of this testing just today since today is when I discovered and ran into all of this.

**Comment by guihkx** [comment] 2024-03-16 08:22
I set up a XFCE virtual machine with Arch Linux to test this with the latest version of both xdg-desktop-portal and xdg-desktop-portal-gtk.

To my surprise, I could reproduce the issue.

Somehow it only happens if the file has no extension, though.

Can you please confirm this? I.e. manually type the file extension.

**Comment by guihkx** [comment] 2024-03-16 09:29
Also reproducible on Plasma 6 if I uncheck this option:

![image](https://github.com/flathub/org.avidemux.Avidemux/assets/626206/3dcdf0d4-b9e6-424d-b7e7-8539b4948a8e)

Of course I also have to type a file name without the extension.

This actually looks like a bug in Avidemux... I'll investigate.

**Comment by NintendoManiac64** [comment] 2024-03-16 18:26
The file extension does indeed seem to the at fault—manually typing the file extension makes things work as expected.

It may be worth mentioning that a program like XnView MP (flatpak version of course) behaves the exact same way as Avidemux whereby it also automatically applies a file extension if you don't type it, yet it lacks this issue.

**Closed** 2024-03-16 20:52 UTC

**Comment by NintendoManiac64** [comment] 2024-03-16 21:12
I forgot to mention, as an alternative to automatically appending the file extension, would it be possible to simply auto-fill a file name + extension by default, or should this be something brought up with upstream Avidemux?

**Comment by guihkx** [comment] 2024-03-16 21:37
Avidemux already does that, but it's up to the current portal file chooser implementation to honor it.

The KDE portal honors it by default, through that [checkbox I had to deselect](https://github.com/flathub/org.avidemux.Avidemux/issues/22#issuecomment-2001926434) for the file to be saved without an extension.

That is also honored by the GNOME portal:

https://github.com/flathub/org.avidemux.Avidemux/assets/626206/1a6c9cac-43da-44f9-9c12-5aa83405fb28

For the GTK portal (used by Mint + XFCE), however, that feature [doesn't seem to be implemented](https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191), unfortunately.
