### ISSUE TITLE
Avidemux just crashes after opening, no crash logs.

### ISSUE THREAD

**Issue by lavadrop** [flathub/org.avidemux.Avidemux#21] opened 2024-03-08 05:24 UTC
It stays open for about 6 seconds then crashes.
openSUSE Tumbleweed running on Wayland in Plasma 5.27.10, Flatpak Mesa 23.3.5.
[avidemux_flatpak_start-log.txt](https://github.com/flathub/org.avidemux.Avidemux/files/14533535/avidemux_flatpak_start-log.txt)

**Comment by guihkx** [comment] 2024-03-08 06:04
Do you know what kind of crash?

`coredumpctl list --no-pager` could give us a clue.

**Comment by lavadrop** [comment] 2024-03-09 02:10
```
TIME                         PID  UID  GID SIG     COREFILE EXE                         SIZE
Thu 2024-03-07 22:09:27 CST 8566 1000 1000 SIGQUIT present  /usr/lib64/firefox/firefox 18.2M
```

**Comment by guihkx** [comment] 2024-03-09 03:56
Is that the only crash log you have? Then I think Avidemux isn't *really* crashing...

Can you record a video of the behavior, perhaps?

By the way, your log file looks pretty much like mine (except for a few differences related to AMD/NVIDIA). My log also shows this at the end:

```
...
ignored: jobs
ignored: custom
ignored: QtSettings.ini
ignored: jobs.sql
ignored: config3
0 : /home/gui/.avidemux6//lastEdit.py
No crash file (/home/gui/.avidemux6/crash.py)
```

But Avidemux doesn't crash/close for me.

**Comment by lavadrop** [comment] 2024-03-09 04:21
Sure 

https://github.com/flathub/org.avidemux.Avidemux/assets/6760790/aa097d18-ebd2-4ba0-8bdc-e4ac29c88aab

**Comment by guihkx** [comment] 2024-03-09 04:24
How strange.

What if you run this in one terminal window:

```
journalctl -f
```

Then run Avidemux again, wait for it to crash, and then check back on the first terminal window to see if anything relevant popped up.

**Comment by lavadrop** [comment] 2024-03-09 06:04
[avidemux-journal-log.txt](https://github.com/flathub/org.avidemux.Avidemux/files/14545170/avidemux-journal-log.txt)

**Comment by guihkx** [comment] 2024-03-09 06:19
Wait, did you enable Wayland with a `flatpak override`, or something? I'm seeing this in the logs:

```
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
```

If you're not sure, please post the result of these commands:

```
$ echo $QT_QPA_PLATFORM
$ cat ~/.local/share/flatpak/overrides/{global,org.avidemux.Avidemux}
```

Because Avidemux really does crash with pure Wayland, and that's why I've removed the `--socket=wayland` permission in 81bdf3e8b5703b52e9f578cc31113f27c474a1e7.

**Comment by lavadrop** [comment] 2024-03-09 06:48
Nope, I haven't modified any settings pertaining to flatpak.
```
echo $QT_QPA_PLATFORM
                                                
```

```
cat ~/.local/share/flatpak/overrides/{global,org.avidemux.Avidemux}
cat: /home/jorgeblasio/.local/share/flatpak/overrides/global: No such file or directory
cat: /home/jorgeblasio/.local/share/flatpak/overrides/org.avidemux.Avidemux: No such file or directory

**Comment by guihkx** [comment] 2024-03-09 06:52
Uh... I guess I'll have to spin up a VM to try and reproduce the crash myself...

But just one last shot, please see if this prevents the crash:

```
flatpak run --env=QT_QPA_PLATFORM=xcb org.avidemux.Avidemux
```

**Comment by lavadrop** [comment] 2024-03-09 06:55
Nice try but no :(

**Comment by guihkx** [comment] 2024-03-09 07:09
Alright, thank you for trying anyway. Maybe I forgot the most obvious thing, what is the exit code of Avidemux?

```sh
flatpak run org.avidemux.Avidemux
echo $? # if using bash
```

**Comment by lavadrop** [comment] 2024-03-09 20:22
137

**Comment by guihkx** [comment] 2024-03-09 21:00
An exit code of 137 seems to indicate that Avidemux was SIGKILL'd.

That could be for a variety of reasons, but a system running out of memory seems to be the most common cause.

Maybe you can check on `htop` (or any other system monitoring tool) how much RAM Avidemux uses before it get (supposedly) killed.

**Comment by lavadrop** [comment] 2024-03-10 04:29
It happens so fast I can barely take a screenshot before it dies.
![Screenshot_20240309_222713](https://github.com/flathub/org.avidemux.Avidemux/assets/6760790/2d9e0670-da7a-4850-8fb6-3f5a3e662f13)

**Comment by guihkx** [comment] 2024-03-10 05:34
Another naïve idea:

1. Start a screen recording
2. Open a terminal window, right click on its title bar, go to "More Actions" and enable "Keep Above Others"
3. Now run this command:

```
flatpak run org.avidemux.Avidemux &>/dev/null & watch -n.1 free -m
```

If this crash is caused by Avidemux exhausting your system's memory, we should be able to see it in the video.

**Comment by lavadrop** [comment] 2024-03-18 20:38
[Videocaptura de pantalla_20240318_143431.webm](https://github.com/flathub/org.avidemux.Avidemux/assets/6760790/a71d73eb-d72f-4f61-99c9-6263b3d98450)

**Comment by guihkx** [comment] 2024-03-18 21:04
Thank you for the video. Memory usage looks absolutely normal to me.

Can you verify that Avidemux has permission to be running in the background?

```
flatpak permission-show org.avidemux.Avidemux | grep background
```

If it does have permission, you should get this output:

```
background      background      org.avidemux.Avidemux   yes     0x00
```

If it doesn't, please give it permission with:

```
flatpak permission-set background background org.avidemux.Avidemux yes
```

Then re-open Avidemux, and try again.

**Comment by lavadrop** [comment] 2024-03-18 23:13
It appears that was it. I wonder if I did something or it was misconfigured from install?

**Comment by guihkx** [comment] 2024-03-18 23:25
I'm not sure but [this person on Reddit](https://www.reddit.com/r/linux_gaming/comments/1bfjdrs/need_help_with_making_flatpak_steam_running_again/) recently had the same problem, but with a different app.

You both use KDE, so maybe it's somehow related to that...

In any case, it's an issue out of scope for this app, so I'll close this one now.

**Closed by guihkx** 2024-03-18 23:25 UTC
